services:
  - type: web
    name: sports-quiz-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

    cronJobs:
  - name: daily-question-generator
    # Schedule runs at 5:00 AM UTC every day. Adjust as needed.
    # Use https://crontab.guru/ to help define schedules.
    schedule: "6 12 * * *"
    # Command to execute the TypeScript script using tsx
    command: "npx tsx scripts/generate-daily-questions.ts"
