services:
  - type: web
    name: sports-quiz-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1